<?php

declare(strict_types=1);

namespace App\Domain\Preparation\Documents;

/**
 * The one place a document object key is built.
 *
 * Keys are content-addressed and scoped by workspace and document:
 *
 *     documents/{workspace public id}/{document public id}/{kind}-{sha256}.pdf
 *
 * Three properties follow, and each of them is load-bearing:
 *
 *  1. **Nothing is ever overwritten.** Different bytes produce a different key, so a write
 *     can only ever replace an object with itself. That is what makes "retain the original
 *     byte-for-byte" a property of the key layout rather than a rule someone has to
 *     remember.
 *  2. **A key is verifiable on its own.** The digest of the object's contents has to equal
 *     the digest in its own name, which is what the read-back check at intake asserts.
 *  3. **The prefix is a tenancy boundary.** Everything belonging to one workspace sits
 *     under one prefix, so retention, export, and the orphan pruner can reason per
 *     workspace without a join.
 *
 * The ULIDs are generated by the application and are already URL-safe; the digest is hex.
 * Nothing here is derived from a filename supplied by the uploader, so a hostile filename
 * cannot influence the key.
 */
final readonly class DocumentStorageKey
{
    private function __construct(public string $value) {}

    public static function for(string $workspacePublicId, string $documentPublicId, RevisionKind $kind, string $sha256): self
    {
        return new self(sprintf(
            'documents/%s/%s/%s-%s.pdf',
            self::segment($workspacePublicId, 'workspace public id'),
            self::segment($documentPublicId, 'document public id'),
            $kind->value,
            self::digest($sha256),
        ));
    }

    public function __toString(): string
    {
        return $this->value;
    }

    private static function segment(string $value, string $label): string
    {
        if (preg_match('/^[0-9A-Za-z]{10,64}$/', $value) !== 1) {
            throw new \InvalidArgumentException("The {$label} is not a usable storage key segment.");
        }

        return $value;
    }

    private static function digest(string $sha256): string
    {
        if (preg_match('/^[0-9a-f]{64}$/', $sha256) !== 1) {
            throw new \InvalidArgumentException('A storage key needs a lowercase hex SHA-256 digest.');
        }

        return $sha256;
    }
}
