<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * The snapshot a sender actually sends.
 *
 * One row holds everything docs/HANDOFF.md section 6 requires a version to capture: the PDF
 * revision, the recipients/roles, the field definitions, the consent policy version, and the
 * rendering settings. Sending copies these values into the envelope, so a later template
 * edit cannot reach an envelope that is already out — the edit becomes a new version, and
 * the old row is never touched.
 *
 * ## Immutable after publish
 *
 * `published_at` is the lock. Before it is set the row is a draft and may be edited freely;
 * once it is set, App\Domain\Preparation\Templates\Models\TemplateVersion refuses updates and
 * deletes with a typed exception. Enforcement is in the model rather than a database trigger
 * for the reason `document_revisions` and `esign_audit_events` give: triggers are not
 * portable across SQLite, MySQL, and MariaDB. There is a `created_at` and no `updated_at`,
 * because the only permitted mutation of a version's own row is the publish stamp.
 *
 * ## Columns that are not obvious
 *
 * `version` is a per-template counter starting at 1, unique with `template_id`. It is the
 * number a human quotes ("we sent v3"), it is stable, and the unique key is what makes two
 * concurrent drafts of the same number a database error rather than an ambiguity.
 *
 * `document_revision_id` points at the **review** revision (`document_revisions.kind =
 * 'review'`) of a `ready` document — the immutable bytes a signer may be shown. It is not
 * the document id: binding a version to a document would let a re-upload change what a
 * template means, and architecture invariant 2 binds an acceptance to a specific revision.
 * RESTRICT, so a revision cannot be deleted out from under a version.
 *
 * `field_schema` is the canonical field schema document
 * (App\Domain\Preparation\Schema\FieldSchemaDocument::canonicalJson(), decoded).
 * `field_schema_sha256` is the digest of those canonical bytes. It is stored rather than
 * recomputed on read because a MySQL `JSON` column does not preserve object key order, so
 * the bytes that come back out of this column are not necessarily the bytes that went in.
 * The canonical form is therefore always regenerated by re-importing the decoded value
 * (`TemplateVersion::canonicalFieldSchemaJson()`), which is order-insensitive and yields the
 * same digest on every engine. Never hash the raw column.
 *
 * `recipients` is the roles/placeholders list from the same schema document, denormalised so
 * the Signing module can read who a template expects without parsing the whole field set.
 * It is written from the schema and never independently: the two cannot disagree.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('template_versions', function (Blueprint $table): void {
            $table->id();
            $table->ulid('public_id')->unique();
            $table->foreignId('template_id')->constrained('templates')->restrictOnDelete();
            $table->unsignedInteger('version');

            // The review revision this version snapshots. See the class docblock.
            $table->foreignId('document_revision_id')->constrained('document_revisions')->restrictOnDelete();

            $table->json('field_schema');
            $table->char('field_schema_sha256', 64);
            $table->json('recipients');

            // The consent text version a signer will be shown and that the attestation will
            // record. A string, not a foreign key: the consent policy is deployment
            // configuration and its history outlives any table this application owns.
            $table->string('consent_policy_version', 64);

            $table->json('render_settings');

            // Null while the version is a draft. Setting it is the one permitted update.
            $table->timestamp('published_at')->nullable();

            $table->foreignId('created_by')->nullable()->constrained('users')->restrictOnDelete();
            $table->timestamp('created_at')->nullable();

            $table->unique(['template_id', 'version']);
            $table->index(['template_id', 'published_at']);
            $table->index('document_revision_id');
            $table->index('field_schema_sha256');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('template_versions');
    }
};
